### ISSUE TITLE
Add Scrivener to supported editors

### ISSUE THREAD

**Issue by iandol** [mcanouil/awesome-quarto#102]
### Link to suggestion

https://github.com/iandol/scrivomatic/blob/master/Scivener+Quarto.md

### Targeted section

Supported editors

### Describe your suggestion

[Scrivener](https://www.literatureandlatte.com) is a long-form writing tool, managing research, notes, figures and more all in one interface while you focus on your manuscript text. It separates editor formatting from final formatting using a flexible compiler system. Scrivener therefore maps any editor formatting to multiple output formats, including Pandoc-flavoured markdown. It can also run post-processing tools. To support Quarto's cross-referencing system, I wrote a small script that structures the cross-referencing labels to be compatible with Scrivener's editor and then automatically run Quarto directly from Scrivener's document compiler.

### Checklist

- [X] checked if your suggestion is not already listed in __Awesome Quarto__ list.
- [X] checked if it can fit in an existed section or [open a discussion](https://github.com/mcanouil/awesome-quarto/discussions/new?category=ideas) to suggest any new sections..
- [X] checked when it's a repository if it's maintained (archived repository will be rejected).

**Comment by mcanouil** [comment]
Thanks for your suggestion!

This tool does not seem free, also I would prefer to include a link to Scrivener where the compatibility with Quarto is clearly documented rather than some "random" markdown file in a repository.

**Comment by iandol** [comment]
Scrivener is a commercial editor, that is correct, but it is used by many writers including academics who benefit from its unique feature set for long-form writing (I am a user, and not affiliated in any way with them). You include Sublime Text which is also a commercial editor so it at least seems unfair to exclude one commercial tool but include another. 

But yes, my guide details how one needs to adapt the Pandoc output to work with Quarto, and I doubt Scrivener will add specific support for Quarto in the near term "officially". I could add this as a post to their official forums if you prefer a forum post to a markdown document? Please close if this still does not match your requirements, and thanks for your work compiling this list!

**Comment by mcanouil** [comment]
The not-free part is not really a criteria for inclusion or exclusion.

My main "concern" is that the markdown file is kind of hidden in a repository and the workflow is not really clear, _i.e._, "this script", "this workflow", but no script nor workflow are described. An example is provided, but it's a zip archive which can't be seen without downloading it first. Also, the user have to leave the page and click on links to some other resources.
In its current state, I do not think it can easily be used by anyone but you.

**Comment by iandol** [comment]
Thanks Mickaël.

Scrivener projects are folder bundles (a common document format on macOS), and have to be zipped to share them. My [scrivener + pandoc workflow «248 stars»](https://github.com/iandol/scrivomatic), and many other sample projects in our community do the same thing.

I have [re]written a Scrivener forum post on Scrivener + Quarto, you may find this preferable to use as a link as it is more discursive:

https://forum.literatureandlatte.com/t/scrivener-quarto-a-technical-academic-publishing-workflow/129769

Note: I've been a Scrivener forum member since 2007 and published >1400 posts.

**Comment by mcanouil** [comment]
I find your forum post easier to follow and definitely clearer.
Thanks for improving this, I'll add it for the next release.

**Comment by iandol** [comment]
Thanks Mickaël. I've converted the project download into a Scrivener Template, which is the "official" extension mechanism for these kinds of things. I will keep that updated, and add a link to your list from that forum post too.

**Comment by mcanouil** [comment]
Just added!
