### ISSUE TITLE
Quarto used for documentation for a simple package

### ISSUE THREAD

**Issue by aeturrell** [mcanouil/awesome-quarto#11]
### Link to suggestion

https://aeturrell.github.io/skimpy/

### Describe your suggestion

You could add https://aeturrell.github.io/skimpy/ as an example of Quarto being used for documentation of a package. There's a makefile that turns a Jupyter notebook into a website via Quarto (link here: https://github.com/aeturrell/skimpy/blob/main/Makefile).

**Comment by mcanouil** [comment]
This would be an example, right?
For example, there is https://github.com/edgararuiz/ecodown which is a tool to make R package documentation into a Quarto website.

Me being curious, it does not seem the documentation is built upon the Docstring Conventions, it is rather hard written in a jupyter notebook used as the index of the gh-page, am I correct?

**Comment by aeturrell** [comment]
Yeah, this is very much not a proper or automated documentation tool so happy to close this on that basis (thinking was very much "here's an interesting example").

**Comment by mcanouil** [comment]
I think it's fine for now as an example.
But likely to be removed if an automated tool is developed.
