### ISSUE TITLE
Docker images for GitLab CI

### ISSUE THREAD

**Issue by rgaiacs** [mcanouil/awesome-quarto#123]
### Link to suggestion

https://gitlab.com/quarto-forge/docker

### Targeted section

Continuous integration / Continuous deployment

### Describe your suggestion

This is shameless self promotion. :-D

This is a collection of Docker images for people that want to use Quarto in GitLab CI.

### Checklist

- [X] checked if your suggestion is not already listed in __Awesome Quarto__ list.
- [X] checked if it can fit in an existed section or [open a discussion](https://github.com/mcanouil/awesome-quarto/discussions/new?category=ideas) to suggest any new sections..
- [X] checked when it's a repository if it's maintained (archived repository will be rejected).

**Comment by mcanouil** [comment]
Thanks for the suggestion!

Could you develop a bit the purpose of your Docker images in the context of Quarto and also how it differs (or not) from the Docker images from <https://rocker-project.org/> which now include Quarto along with several other tools?

**Comment by rgaiacs** [comment]
> Could you develop a bit the purpose of your Docker images in the context of Quarto

I wanted a "small" image to build documents to HTML and other formats.

> how it differs (or not) from the Docker images from https://rocker-project.org/

rocker is a great project and I got inspiration from it. rocker is focus on R and R Studio. I'm also looking at Python.

**Comment by mcanouil** [comment]
Ok, I'll need to think more about this, because it might require a new section and some other item might also be needed into that section.

**Comment by mcanouil** [comment]
I don't think I am not going to add Docker images (this one or others) to Awesome Quarto, since it's not focused on Quarto.
