### ISSUE TITLE
Research lab website

### ISSUE THREAD

**Issue by jmgirard** [mcanouil/awesome-quarto#127]
### Link to suggestion

https://affcom.ku.edu

### Targeted section

Real life examples/Websites formats

### Describe your suggestion

This is a real-life example of using Quarto to build a website for a research lab, including listing pages for people, publications, and blog posts. The repository is: https://github.com/jmgirard/affcomlab. Some explanation of the publications part: https://github.com/quarto-dev/quarto-cli/issues/1324#issuecomment-1252961320

Note that, if you want a specific title, you can use "AffCom Lab Website" or just keep the generic "Research lab website"

### Checklist

- [X] checked if your suggestion is not already listed in __Awesome Quarto__ list.
- [X] checked if it can fit in an existed section or [open a discussion](https://github.com/mcanouil/awesome-quarto/discussions/new?category=ideas) to suggest any new sections..
- [X] checked when it's a repository if it's maintained (archived repository will be rejected).

**Comment by mcanouil** [comment]
Thank you for this suggestion!

I'll add this in the example section. a bit later.
