### ISSUE TITLE
Creating your personal website using Quarto

### ISSUE THREAD

**Issue by samanthacsik** [mcanouil/awesome-quarto#133]
### Link to suggestion

https://ucsb-meds.github.io/creating-quarto-websites/

### Targeted section

Tutorials & workshops

### Describe your suggestion

A step-by-step guide for setting up a personal website using Quarto -- instructions include both RStudio and command line workflows. We'll be teaching this each year to new cohorts of Master of Environmental Data Science students and plan to maintain/update as needed!

### Checklist

- [X] checked if your suggestion is not already listed in __Awesome Quarto__ list.
- [X] checked if it can fit in an existed section or [open a discussion](https://github.com/mcanouil/awesome-quarto/discussions/new?category=ideas) to suggest any new sections..
- [X] checked when it's a repository if it's maintained (archived repository will be rejected).

**Comment by mcanouil** [comment]
Thanks, added to the list!
