### ISSUE TITLE
a simple matrix-quarto-bot for pdf-files

### ISSUE THREAD

**Issue by produnis** [mcanouil/awesome-quarto#138]
### Link to suggestion

https://github.com/rgomez90/matrix-bot

### Targeted section

Libraries/Packages/Scripts

### Describe your suggestion

A little bot for the matrix-network that listens for some .qmd-files and returns the pdf into the matrix channel.
This brings quarto to your smartphone ;)
As I am rendering my official letters with quarto, I am now able to do so on my Android or iPad while being in the metro. :-)
As the Bot will take all files sent to the matrix room, I am able to use images, templates and other .tex-files as well with my .qmd-file.

### Checklist

- [X] checked if your suggestion is not already listed in __Awesome Quarto__ list.
- [X] checked if it can fit in an existed section or [open a discussion](https://github.com/mcanouil/awesome-quarto/discussions/new?category=ideas) to suggest any new sections..
- [X] checked when it's a repository if it's maintained (archived repository will be rejected).

**Comment by mcanouil** [comment]
Thanks, added to the list!
