### ISSUE TITLE
quarto-gouv Quarto template

### ISSUE THREAD

**Issue by mcanouil** [mcanouil/awesome-quarto#160]
### Link to suggestion

https://github.com/spyrales/quarto-gouv

### Targeted section

Templates/Docx Documents

### Describe your suggestion

A Quarto extension for French governmental documents

### Checklist

- [X] checked if your suggestion is not already listed in __Awesome Quarto__ list.
- [X] checked if it can fit in an existed section or [open a discussion](https://github.com/mcanouil/awesome-quarto/discussions/new?category=ideas) to suggest any new sections..
- [X] checked when it's a repository if it's maintained (archived repository will be rejected).

**Comment by mcanouil** [comment]
@RLesur & @ThomasFaria Is it ok to reference the template in Awesome Quarto?

**Comment by RLesur** [comment]
No problem, thx!
