### ISSUE TITLE
Tips to add some personality to your Quarto Blog

### ISSUE THREAD

**Issue by ddanieltan** [mcanouil/awesome-quarto#162]
### Link to suggestion

https://www.ddanieltan.com/posts/blogtips/

### Targeted section

Blog posts

### Describe your suggestion

A blog post sharing some of the added features and tweaks users can make on top of the standard blog templates to inject some personality into their blog.

### Checklist

- [X] checked if your suggestion is not already listed in __Awesome Quarto__ list.
- [X] checked if it can fit in an existed section or [open a discussion](https://github.com/mcanouil/awesome-quarto/discussions/new?category=ideas) to suggest any new sections..
- [X] checked when it's a repository if it's maintained (archived repository will be rejected).

**Comment by mcanouil** [comment]
Thanks for the suggestion!
