### ISSUE TITLE
Tufte book layout for Quarto

### ISSUE THREAD

**Issue by mcanouil** [mcanouil/awesome-quarto#163]
### Link to suggestion

https://github.com/fredguth/tufte-quarto

### Targeted section

Templates/PDF Documents

### Describe your suggestion

Tufte book layout for Quarto

### Checklist

- [X] checked if your suggestion is not already listed in __Awesome Quarto__ list.
- [X] checked if it can fit in an existed section or [open a discussion](https://github.com/mcanouil/awesome-quarto/discussions/new?category=ideas) to suggest any new sections..
- [X] checked when it's a repository if it's maintained (archived repository will be rejected).

**Comment by mcanouil** [comment]
@fredguth I saw this repository few months ago when you posted some questions on GitHub Discussion, at that time it was still in progress. Do you feel it's ready to share?

**Comment by fredguth** [comment]
Yes, it is.
