### ISSUE TITLE
Simple Worksheets Generator

### ISSUE THREAD

**Issue by jmablog** [mcanouil/awesome-quarto#167]
### Link to suggestion

https://github.com/jmablog/simple-worksheets-generator

### Targeted section

Templates/PDF Documents

### Describe your suggestion

A series of templates for a Quarto project to convert a single Markdown input into beautiful and simple Word, HTML, and PDF worksheets. Includes options for auto-linked questions and answer breakouts.

### Checklist

- [X] checked if your suggestion is not already listed in __Awesome Quarto__ list.
- [X] checked if it can fit in an existed section or [open a discussion](https://github.com/mcanouil/awesome-quarto/discussions/new?category=ideas) to suggest any new sections..
- [X] checked when it's a repository if it's maintained (archived repository will be rejected).

**Comment by mcanouil** [comment]
Thanks for your suggestion!
As is, your template is not exactly easy to use for Quarto user, _i.e_, it would be probably better to make your template as an extension template/format (see <https://quarto.org/docs/extensions/>).

**Comment by mcanouil** [comment]
I am going to close this in its current form, I don't think it follows Awesome guidelines.
