### ISSUE TITLE
Quantum Jitter

### ISSUE THREAD

**Issue by cgoo4** [mcanouil/awesome-quarto#206]
### Link to suggestion

[quantumjitter.com](https://www.quantumjitter.com/)

### Targeted section

Real life examples/Websites formats

### Describe your suggestion

Quarto R website / blog with a custom theme (adapted from flatly / darkly), day / night landing page and a novel 404.

### Checklist

- [X] checked if your suggestion is not already listed in __Awesome Quarto__ list.
- [X] checked if it can fit in an existed section or suggest a new section and explain why your item does not fit into one and what would be the interest of your new section.
- [X] checked when it's a repository if it's maintained (archived repository will be rejected).

**Comment by mcanouil** [comment]
Thanks for the suggestion.

**Comment by cgoo4** [comment]
Thank you for including this.
