### ISSUE TITLE
code-insertion Quarto extension

### ISSUE THREAD

**Issue by mcanouil** [mcanouil/awesome-quarto#207]
### Link to suggestion

https://github.com/feynlee/code-insertion

### Targeted section

Extensions

### Describe your suggestion

This is a [Quarto](https://quarto.org/) extension that enables code insertion immediately before and/or after a post/page.

### Checklist

- [X] checked if your suggestion is not already listed in __Awesome Quarto__ list.
- [X] checked if it can fit in an existed section or suggest a new section and explain why your item does not fit into one and what would be the interest of your new section.
- [X] checked when it's a repository if it's maintained (archived repository will be rejected).

**Comment by mcanouil** [comment]
@feynlee FYI, I am going to add your extension in the list. 😉

**Comment by feynlee** [comment]
Thanks! 🥳
