### ISSUE TITLE
RStudio IDE 

### ISSUE THREAD

**Issue by EmilHvitfeldt** [mcanouil/awesome-quarto#222]
### Link to suggestion

https://posit.co/products/open-source/rstudio/

### Targeted section

Supported editors

### Describe your suggestion

I feel like the RStudio IDE should be listed under supported editors

### Checklist

- [X] checked if your suggestion is not already listed in __Awesome Quarto__ list.
- [X] checked if it can fit in an existed section or suggest a new section and explain why your item does not fit into one and what would be the interest of your new section.
- [X] checked when it's a repository if it's maintained (archived repository will be rejected).

**Comment by mcanouil** [comment]
Indeed, for some reason I thought I already added it 🤦‍♂️
