### ISSUE TITLE
Mi primer blog con Quarto

### ISSUE THREAD

**Issue by perezp44** [mcanouil/awesome-quarto#223]
### Link to suggestion

https://perezp44.github.io/taller.primer.blog/

### Targeted section

Tutorials & workshops

### Describe your suggestion

A website with the materials for a workshop to create a blog with Quarto. The workshop was given at the [I Congreso & XII Jornadas de Usuarios de R](http://r-es.org/12jr/) held in Córdoba (Spain). The workshop website contains slides, tutorials, and a blog. The materials are all written in Spanish. The repo is [here](https://github.com/perezp44/taller.primer.blog).

### Checklist

- [X] checked if your suggestion is not already listed in __Awesome Quarto__ list.
- [X] checked if it can fit in an existed section or suggest a new section and explain why your item does not fit into one and what would be the interest of your new section.
- [X] checked when it's a repository if it's maintained (archived repository will be rejected).

**Comment by mcanouil** [comment]
Thanks for the suggestion!
This is great to have content bot in English.

**Comment by perezp44** [comment]
Thanks to you for your awesome list!!
