### ISSUE TITLE
chord-sheet Quarto extension

### ISSUE THREAD

**Issue by mcanouil** [mcanouil/awesome-quarto#226]
### Link to suggestion

https://github.com/dfalbel/chord-sheet

### Targeted section

Extensions

### Describe your suggestion

> This extension provides support for rendering chord sheets in [Quarto](https://quarto.org/) HTML documents. It uses the [ChordSheetJS](https://github.com/martijnversluis/ChordSheetJS) library to parse and render sheets into HTML tables.

### Checklist

- [X] checked if your suggestion is not already listed in __Awesome Quarto__ list.
- [X] checked if it can fit in an existed section or suggest a new section and explain why your item does not fit into one and what would be the interest of your new section.
- [X] checked when it's a repository if it's maintained (archived repository will be rejected).

**Comment by mcanouil** [comment]
@dfalbel I have found your Quarto extension on GitHub. Is it ok for me to include it here, in particular, is it stable ?

**Comment by dfalbel** [comment]
Sure! It's fine to include it. I haven't been using it recently, but should be stable enough as we vendor the js library altogether.
