### ISSUE TITLE
qletter Quarto template

### ISSUE THREAD

**Issue by mcanouil** [mcanouil/awesome-quarto#230]
### Link to suggestion

https://github.com/juliantao/qletter

### Targeted section

Templates/PDF Documents

### Describe your suggestion

> This is a Quarto template that assists you in writing a letter.
> 
> The template is based on the LaTex letter class, with a customized layout including a logo at the upper left, a name block on the upper right, and an address block at the bottom left of the first page.

### Checklist

- [X] checked if your suggestion is not already listed in __Awesome Quarto__ list.
- [X] checked if it can fit in an existed section or suggest a new section and explain why your item does not fit into one and what would be the interest of your new section.
- [X] checked when it's a repository if it's maintained (archived repository will be rejected).

**Comment by mcanouil** [comment]
@juliantao I have found your Quarto extension on GitHub. Is it ok for me to include it here, in particular, is it stable?

**Comment by juliantao** [comment]
Thank you for reaching out, @mcanouil. It is stable. Feel free to include in the list. Thanks!
