### ISSUE TITLE
naletter Quarto template

### ISSUE THREAD

**Issue by mcanouil** [mcanouil/awesome-quarto#232]
### Link to suggestion

https://github.com/nareal/naletter

### Targeted section

Templates/PDF Documents

### Describe your suggestion

> This is a [Quarto](https://quarto.org/) extension to provide a PDF letter template.

### Checklist

- [X] checked if your suggestion is not already listed in __Awesome Quarto__ list.
- [X] checked if it can fit in an existed section or suggest a new section and explain why your item does not fit into one and what would be the interest of your new section.
- [X] checked when it's a repository if it's maintained (archived repository will be rejected).

**Comment by mcanouil** [comment]
@nareal I have found your Quarto extension on GitHub. Is it ok for me to include it here, in particular, is it stable?

**Comment by nareal** [comment]
Yes, please feel free to include the link. I have been using it without issues. I'll be glad to address any problems that others identify.
