### ISSUE TITLE
rev-history Quarto extension

### ISSUE THREAD

**Issue by mcanouil** [mcanouil/awesome-quarto#235]
### Link to suggestion

https://github.com/smutch/quarto-rev-history

### Targeted section

Extensions

### Describe your suggestion

> Generates a simple revision history table with content pulled from git tags.

### Checklist

- [X] checked if your suggestion is not already listed in __Awesome Quarto__ list.
- [X] checked if it can fit in an existed section or suggest a new section and explain why your item does not fit into one and what would be the interest of your new section.
- [X] checked when it's a repository if it's maintained (archived repository will be rejected).

**Comment by mcanouil** [comment]
@smutch I have found your Quarto extension on GitHub. Is it ok for me to include it here, in particular, is it stable?

**Comment by smutch** [comment]
Absolutely! Thanks for getting in touch. I'd love for the extension to be listed. It's pretty bare-bones at the moment, but it is stable and works (I've been using it regularly for the last few weeks). I just tagged and published a v0.1 release.

Thanks for maintaining this list as well. I've used it a number of times and it's a great resource.
