### ISSUE TITLE
verticator Quarto extension

### ISSUE THREAD

**Issue by mcanouil** [mcanouil/awesome-quarto#236]
### Link to suggestion

https://github.com/Martinomagnifico/quarto-verticator

### Targeted section

Extensions

### Describe your suggestion

> A quarto extension for [Reveal.js](https://revealjs.com/) that adds indicators to show the amount of slides in a vertical stack.

### Checklist

- [X] checked if your suggestion is not already listed in __Awesome Quarto__ list.
- [X] checked if it can fit in an existed section or suggest a new section and explain why your item does not fit into one and what would be the interest of your new section.
- [X] checked when it's a repository if it's maintained (archived repository will be rejected).

**Comment by mcanouil** [comment]
@martinomagnifico I have found your Quarto extension on GitHub. Is it ok for me to include it here, in particular, is it stable?

**Comment by Martinomagnifico** [comment]
Yes not a problem. The Quarto version is technically the same as the regular npm version, and is stable.
