### ISSUE TITLE
monash-quarto-letter Quarto template

### ISSUE THREAD

**Issue by mcanouil** [mcanouil/awesome-quarto#238]
### Link to suggestion

https://github.com/robjhyndman/monash-quarto-letter

### Targeted section

Templates/PDF Documents

### Describe your suggestion

> This is a Quarto template that assists you in creating a letter on Monash University letterhead

### Checklist

- [X] checked if your suggestion is not already listed in __Awesome Quarto__ list.
- [X] checked if it can fit in an existed section or suggest a new section and explain why your item does not fit into one and what would be the interest of your new section.
- [X] checked when it's a repository if it's maintained (archived repository will be rejected).

**Comment by robjhyndman** [comment]
Sure. It's very specific to Monash Business School, but someone might find it useful to adapt to their own institution. We have written an R package ([github.com/numbats/monash](https://github.com/numbats/monash)) with a lot of Rmarkdown templates for our staff and students. This is the first template we have ported to quarto. I plan to create quarto versions of the others as well.

**Comment by robjhyndman** [comment]
We now have three quarto extensions:

- https://github.com/numbats/monash-quarto-letter
- https://github.com/numbats/monash-quarto-memo
- https://github.com/numbats/monash-quarto-workingpaper

**Comment by robjhyndman** [comment]
And two more:

- https://github.com/numbats/monash-quarto-report
- https://github.com/numbats/monash-quarto-thesis

**Comment by mcanouil** [comment]
Oh!
Maybe it would be best for users if all the extensions were actually one, i.e., an extension can include multiple formats and share components.
See <https://github.com/davidcarayon/quarto-inrae-extension> for a French public institute.
Although, I need to double check if an extension can have multiple "pdf" formats or if it can have only one of each default formats.

**Comment by mcanouil** [comment]
I opened a discussion: https://github.com/quarto-dev/quarto-cli/discussions/3733

I believe it would makes thing easier for organisations/institutions if all formats could be embedded in one Quarto extension, thus share resources (logo, etc.).

**Comment by robjhyndman** [comment]
Sure. Good idea. The thesis one needs to be separate because it is more than an extension. The others can probably be combined.

**Comment by mcanouil** [comment]
Different YAML header is not really an issue: see <https://github.com/nmfs-opensci/quarto_titlepages>.


Another way to centralise your Monash extensions and possibly the easiest (only) way right now would be to use git modules in new repository. For example, you can take a look at <https://github.com/mcanouil/publishing-templates> (not perfect, but should give you some ideas).
