### ISSUE TITLE
multibib Quarto extension

### ISSUE THREAD

**Issue by mcanouil** [mcanouil/awesome-quarto#241]
### Link to suggestion

https://github.com/pandoc-ext/multibib

### Targeted section

Extensions

### Describe your suggestion

This filter allows to create multiple bibliographies using citeproc.

### Checklist

- [X] checked if your suggestion is not already listed in __Awesome Quarto__ list.
- [X] checked if it can fit in an existed section or suggest a new section and explain why your item does not fit into one and what would be the interest of your new section.
- [X] checked when it's a repository if it's maintained (archived repository will be rejected).

**Comment by mcanouil** [comment]
FYI @tarleb

**Comment by tarleb** [comment]
:tada: Thanks!
