### ISSUE TITLE
Extensions about author block

### ISSUE THREAD

**Issue by cderv** [mcanouil/awesome-quarto#255]
### Link to suggestion

https://github.com/kapsner/authors-block

### Targeted section

Require a new section (please describe below)

### Describe your suggestion

Maybe useful to add it the list of Extensions ? I did not know it existed.

### Checklist

- [X] checked if your suggestion is not already listed in __Awesome Quarto__ list.
- [X] checked if it can fit in an existed section or suggest a new section and explain why your item does not fit into one and what would be the interest of your new section.
- [X] checked when it's a repository if it's maintained (archived repository will be rejected).

**Comment by mcanouil** [comment]
I noticed this one recently.
Unfortunately, the repository does not have any tag, this is why even if it's a month old it never appeared in my searches on GitHub. 🤷‍♂️

**Comment by cderv** [comment]
yeah. Good call opening an issue there to ask to add! 👍
