### ISSUE TITLE
Institute of Physics (IOP) Quarto Journal template

### ISSUE THREAD

**Issue by mcanouil** [mcanouil/awesome-quarto#259]
### Link to suggestion

https://github.com/sebdunnett/quarto-iop

### Targeted section

Templates/Journals

### Describe your suggestion

This Quarto format will help you create documents for journals published by IOP. 

### Checklist

- [X] checked if your suggestion is not already listed in __Awesome Quarto__ list.
- [X] checked if it can fit in an existed section or suggest a new section and explain why your item does not fit into one and what would be the interest of your new section.
- [X] checked when it's a repository if it's maintained (archived repository will be rejected).

**Comment by sebdunnett** [comment]
New to GitHub/Quarto etc. and was looking to see how I get people to start using the template. Saw this and mistakenly thought someone had already done one 😆 

Thanks for picking it up, I think it's at the stage now for use.
