### ISSUE TITLE
Quarto Extension for hiding comments from code chunk in the rendered output

### ISSUE THREAD

**Issue by shafayetShafee** [mcanouil/awesome-quarto#284]
### Link to suggestion

https://github.com/shafayetShafee/hide-comment

### Targeted section

Extensions

### Describe your suggestion

I wish to see [`hide-comment`](https://github.com/shafayetShafee/hide-comment) enlisted here which can be used to hide comments used in the code chunk (but will be hidden in the rendered output)

### Checklist

- [X] checked if your suggestion is not already listed in __Awesome Quarto__ list.
- [X] checked if it can fit in an existed section or suggest a new section and explain why your item does not fit into one and what would be the interest of your new section.
- [X] checked when it's a repository if it's maintained (archived repository will be rejected).

**Comment by mcanouil** [comment]
Thanks for the PR #285
