### ISSUE TITLE
Quarto-based template for uni course websites

### ISSUE THREAD

**Issue by jonjoncardoso** [mcanouil/awesome-quarto#294]
### Link to suggestion

https://github.com/jonjoncardoso/quarto-template-for-university-courses

### Targeted section

Repository templates

### Describe your suggestion

A quarto-based GitHub repository template for designing uni course websites. It already comes with sleek RevealJS templates and multi-year support. Plus, automated publishing to GitHub Pages.

### Checklist

- [X] checked if your suggestion is not already listed in __Awesome Quarto__ list.
- [X] checked if it can fit in an existed section or suggest a new section and explain why your item does not fit into one and what would be the interest of your new section.
- [X] checked when it's a repository if it's maintained (archived repository will be rejected).

**Comment by mcanouil** [comment]
Thanks for the suggestion.
Added to the list (note that in the future, it's highly possible that extensions will me moved elsewhere)
