### ISSUE TITLE
A Quarto filter to format the python codes using black code formatter

### ISSUE THREAD

**Issue by shafayetShafee** [mcanouil/awesome-quarto#295]
### Link to suggestion

https://github.com/shafayetShafee/black-formatter

### Targeted section

Extensions

### Describe your suggestion

I wish to see [`black-formatter`](https://github.com/shafayetShafee/black-formatter) to be enlisted here using which it is possible to format the codes in python code chunk.

### Checklist

- [X] checked if your suggestion is not already listed in __Awesome Quarto__ list.
- [X] checked if it can fit in an existed section or suggest a new section and explain why your item does not fit into one and what would be the interest of your new section.
- [X] checked when it's a repository if it's maintained (archived repository will be rejected).

**Comment by mcanouil** [comment]
Added to the list (note that in the future, it's highly possible that extensions will me moved elsewhere).
