### ISSUE TITLE
embedpdf shortcode Extension

### ISSUE THREAD

**Issue by jmgirard** [mcanouil/awesome-quarto#299]
### Link to suggestion

https://github.com/jmgirard/embedpdf

### Targeted section

Extensions

### Describe your suggestion

This extension provides support for embedding PDF files _(HTML-based format only)._

### Checklist

- [X] checked if your suggestion is not already listed in __Awesome Quarto__ list.
- [X] checked if it can fit in an existed section or suggest a new section and explain why your item does not fit into one and what would be the interest of your new section.
- [X] checked when it's a repository if it's maintained (archived repository will be rejected).

**Comment by mcanouil** [comment]
Thanks for the suggestion.

FYI, I am working for something hopefully better to list extensions and improve searchability et discoverability.

**Comment by mcanouil** [comment]
Added to the list (note that in the future, it's highly possible that extensions will me moved elsewhere).
