### ISSUE TITLE
quarto-cv

### ISSUE THREAD

**Issue by mps9506** [mcanouil/awesome-quarto#303]
### Link to suggestion

https://github.com/mps9506/quarto-cv

### Targeted section

Templates/PDF Documents

### Describe your suggestion

A Quarto pdf template for academic CVs.

### Checklist

- [X] checked if your suggestion is not already listed in __Awesome Quarto__ list.
- [X] checked if it can fit in an existed section or suggest a new section and explain why your item does not fit into one and what would be the interest of your new section.
- [X] checked when it's a repository if it's maintained (archived repository will be rejected).

**Comment by mcanouil** [comment]
Added to the list (note that in the future, it's highly possible that extensions will me moved elsewhere).
