### ISSUE TITLE
Custom numbered blocks

### ISSUE THREAD

**Issue by ute** [mcanouil/awesome-quarto#307]
### Link to suggestion

https://github.com/ute/custom-numbered-blocks

### Targeted section

Extensions

### Describe your suggestion

Quarto extension that provides support for user defined blocks (div classes / latex environments) that can be numbered and crossreferenced. 

- Different classes can share a joint counter,
- by default, blocks are contained in collapsible boxes, like quarto callouts,
- list-of user defined classes can be extracted.

### Checklist

- [X] checked if your suggestion is not already listed in __Awesome Quarto__ list.
- [X] checked if it can fit in an existed section or suggest a new section and explain why your item does not fit into one and what would be the interest of your new section.
- [X] checked when it's a repository if it's maintained (archived repository will be rejected).

**Comment by mcanouil** [comment]
Thanks for the suggestion.
Added to the list (note that in the future, it's highly possible that extensions will me moved elsewhere).
