### ISSUE TITLE
A Quarto filter to run sql queries interactively in html documents

### ISSUE THREAD

**Issue by shafayetShafee** [mcanouil/awesome-quarto#308]
### Link to suggestion

https://github.com/shafayetShafee/interactive-sql

### Targeted section

Extensions

### Describe your suggestion

I wish to see [`interactive-sql`](https://github.com/shafayetShafee/interactive-sql) to be enlisted here with which it is possible to run sql queries from a sqlite database created at the rendering time.

### Checklist

- [X] checked if your suggestion is not already listed in __Awesome Quarto__ list.
- [X] checked if it can fit in an existed section or suggest a new section and explain why your item does not fit into one and what would be the interest of your new section.
- [X] checked when it's a repository if it's maintained (archived repository will be rejected).

**Comment by mcanouil** [comment]
Thanks for the suggestion.
On its way to the list (note that in the future, it's highly possible that extensions will me moved elsewhere).
