### ISSUE TITLE
Update: 360-info/sverto → jimjam-slam/sverto

### ISSUE THREAD

**Issue by jimjam-slam** [mcanouil/awesome-quarto#309]
### Link to suggestion

https://sverto.jamesgoldie.dev

### Targeted section

Update to existing item

### Describe your suggestion

Sverto was accepted in #261. It was originally hosted by @360-info, but as of today it's been migrated to @jimjam-slam.

GitHub redirects old references for the most part. However, the documentation (which was hosted on GitHub Pages) isn't redirected, so that link may need to be updated here! It's now at https://sverto.jamesgoldie.dev.

Sorry for the hassle!

### Checklist

- [X] checked if your suggestion is not already listed in __Awesome Quarto__ list.
- [X] checked if it can fit in an existed section or suggest a new section and explain why your item does not fit into one and what would be the interest of your new section.
- [X] checked when it's a repository if it's maintained (archived repository will be rejected).

**Comment by mcanouil** [comment]
I forgot to mention that it might be moved elsewhere in the future as the list is not supposed to become an extension repository.
I am working on something to list/filter easily extensions that can possibly be integrated or replaced <https://quarto.org/docs/extensions/>.

**Comment by jimjam-slam** [comment]
Awesome to know! If you have any thoughts about which category might be appropriate for Sverto (as it's a combination of custom format and project templates), I'd be happy to see it listed there too 😊
