### ISSUE TITLE
Making Pretty PDFs with Quarto

### ISSUE THREAD

**Issue by nrennie** [mcanouil/awesome-quarto#322]
### Link to suggestion

https://nrennie.rbind.io/blog/making-pretty-pdf-quarto/

### Targeted section

Blog posts

### Describe your suggestion

A blog post showing how to customise the styling of PDF documents, and save the styling into a Quarto extension to make it easier to reuse and share.

### Checklist

- [X] checked if your suggestion is not already listed in __Awesome Quarto__ list.
- [X] checked if it can fit in an existed section or suggest a new section and explain why your item does not fit into one and what would be the interest of your new section.
- [X] checked when it's a repository if it's maintained (archived repository will be rejected).

**Comment by mcanouil** [comment]
Thanks for the suggestion.

Weirdly I was sure I already added it when you published it back in February 🤦‍♂️
