### ISSUE TITLE
New Zealand covid status website

### ISSUE THREAD

**Issue by thoughtfulbloke** [mcanouil/awesome-quarto#323]
### Link to suggestion

https://thoughtfulnz.quarto.pub/nzcovidreport/

### Targeted section

Real life examples/Websites formats

### Describe your suggestion

As an example: once a day I render the site locally (the scripts download all the latest data and renders the graphs and summaries), check it to add any human commentary about significant daily changes, then upload the remote version.

### Checklist

- [X] checked if your suggestion is not already listed in __Awesome Quarto__ list.
- [X] checked if it can fit in an existed section or suggest a new section and explain why your item does not fit into one and what would be the interest of your new section.
- [X] checked when it's a repository if it's maintained (archived repository will be rejected).

**Comment by mcanouil** [comment]
Thanks for the suggestion!

I had a quick look and did not find any particular things in your website.
Did you use anything in addition to the default?
There are already few "default" website, so I don't want to add more.
See for example the last five website in <https://github.com/mcanouil/awesome-quarto#websites-formats>, they all have custom things.

**Comment by mcanouil** [comment]
Thanks again, but I won't include it as it does not seem to include much more than the default website.
