### ISSUE TITLE
dataRetrieval teaching slides

### ISSUE THREAD

**Issue by ldecicco-USGS** [mcanouil/awesome-quarto#325]
### Link to suggestion

https://rconnect.usgs.gov/NMC_dataRetrieval_2

### Targeted section

Real life examples/Presentations formats

### Describe your suggestion

A lot of really specific Quarto features were used to make (what I think) are nice slides used for teaching people how to use the dataRetrieval R package.

There are 2 sets of slides:
https://rconnect.usgs.gov/NMC_dataRetrieval_1
https://rconnect.usgs.gov/NMC_dataRetrieval_2

The code behind the slides are:
https://code.usgs.gov/water/computational-tools/nmc_dataretrieval_1
https://code.usgs.gov/water/computational-tools/nmc_dataretrieval_2

### Checklist

- [X] checked if your suggestion is not already listed in __Awesome Quarto__ list.
- [X] checked if it can fit in an existed section or suggest a new section and explain why your item does not fit into one and what would be the interest of your new section.
- [X] checked when it's a repository if it's maintained (archived repository will be rejected).

**Comment by mcanouil** [comment]
Thanks for the suggestion although I don't think it brings really new things compared to the default slides.
