### ISSUE TITLE
Real World Data Science

### ISSUE THREAD

**Issue by brtarran** [mcanouil/awesome-quarto#326]
### Link to suggestion

https://realworlddatascience.net/

### Targeted section

Real life examples/Websites formats

### Describe your suggestion

Real World Data Science (RWDS) is a new online data science publication, published by the Royal Statistical Society. The site is built in Quarto and features a custom design (built on the Lux Bootswatch theme), with a customised navbar and homepage layout. 

Content on RWDS is free to read and published under Creative Commons licences, and all source code and files can be found in this repository: https://github.com/realworlddatascience/realworlddatascience.github.io.

I'd like to encourage other members of the data science and Quarto communities to discover RWDS and contribute to the development of the site and its content.

Thank you.

### Checklist

- [X] checked if your suggestion is not already listed in __Awesome Quarto__ list.
- [X] checked if it can fit in an existed section or suggest a new section and explain why your item does not fit into one and what would be the interest of your new section.
- [X] checked when it's a repository if it's maintained (archived repository will be rejected).

**Comment by mcanouil** [comment]
Thanks for the suggestion 😉
