### ISSUE TITLE
learning statistics with jamovi

### ISSUE THREAD

**Issue by blacksqr** [mcanouil/awesome-quarto#327]
### Link to suggestion

https://davidfoxcroft.github.io/lsj-book/

### Targeted section

Real life examples/Book formats

### Describe your suggestion

Nice examples of pdf formatting, including inserting LaTex for front and back book cover in output pdf document.

### Checklist

- [X] checked if your suggestion is not already listed in __Awesome Quarto__ list.
- [X] checked if it can fit in an existed section or suggest a new section and explain why your item does not fit into one and what would be the interest of your new section.
- [X] checked when it's a repository if it's maintained (archived repository will be rejected).

**Comment by mcanouil** [comment]
Thanks for the suggestion but I don't think it brings enough new things compared to default book and https://nmfs-opensci.github.io/quarto_titlepages/
