### ISSUE TITLE
Quarto slides from Victorian Biodiversity Conference 2023

### ISSUE THREAD

**Issue by shandiya** [mcanouil/awesome-quarto#329]
### Link to suggestion

https://shandiya.quarto.pub/vicbiocon2023/

### Targeted section

Real life examples/Presentations formats

### Describe your suggestion

These slides are from a talk at the Victorian Biodiversity Conference 2023, titled "Continental-scale biodiversity data assessment using the Atlas of Living Australia". The source code for the slides is available at this Github repository: https://github.com/shandiya/VicBioCon2023. They provide an example of how Python and R code blocks can be included in the same slides as tabs. 

### Checklist

- [X] checked if your suggestion is not already listed in __Awesome Quarto__ list.
- [X] checked if it can fit in an existed section or suggest a new section and explain why your item does not fit into one and what would be the interest of your new section.
- [X] checked when it's a repository if it's maintained (archived repository will be rejected).

**Comment by mcanouil** [comment]
Thanks for the suggestion!
I'll look into it at a later time.
