### ISSUE TITLE
Book suggestion - Introduction to urban accessibility: a practical guide with R

### ISSUE THREAD

**Issue by rafapereirabr** [mcanouil/awesome-quarto#342]
### Link to suggestion

https://ipeagit.github.io/intro_access_book/

### Targeted section

Real life examples/Book formats

### Describe your suggestion

I would like to suggest including the book [**Introduction to urban accessibility: a practical guide with R**](https://ipeagit.github.io/intro_access_book/) to the books section. One nice feature of this book written in Quarto with R is that it is a bilingual book, available both in English and Portuguese.

### Checklist

- [X] checked if your suggestion is not already listed in __Awesome Quarto__ list.
- [X] checked if it can fit in an existed section or suggest a new section and explain why your item does not fit into one and what would be the interest of your new section.
- [X] checked when it's a repository if it's maintained (archived repository will be rejected).

**Comment by mcanouil** [comment]
Thanks for the suggestion.

There is already "classic" book example and yours seems to not use any customise things unfortunately.

**Comment by rafapereirabr** [comment]
Well , our book is bilingual (English and Portuguese). It is super hard to find this in Quarto and ours could serve a an interesting example on how to setup bilingual books. If you don't want to consider the book because the topic is pearhaps a nich, it's fine.

**Comment by mcanouil** [comment]
I completely missed the bilingual part.
Is it only the small link under the table of content? If yes, I would suggest to make it more prominent.

**Comment by rafapereirabr** [comment]
Thanks for the suggestion. I'll check with my co-author @dhersz to see how we could make this more visible, perhaps using babelquarto . At the time we wrote the book, babelquarto still did not exist but used a very similar logic.
