### ISSUE TITLE
Include quato-social-share in the Quarto Extension list

### ISSUE THREAD

**Issue by JauntyJJS** [mcanouil/awesome-quarto#35]
### Link to suggestion

https://github.com/schochastics/quarto-social-share

### Targeted section

Extensions

### Describe your suggestion

This extension allows to add buttons to share articles on various social media platforms.
I have used it in my Quarto Document https://jauntyjjs.github.io/Trelliscopejs_In_Quarto_Example/ 

### Checklist

- [X] checked if your suggestion is not already listed in __Awesome Quarto__ list.
- [X] checked if it can fit in an existed section or [open a discussion](https://github.com/mcanouil/awesome-quarto/discussions/new?category=ideas) to suggest any new sections..
- [X] checked when it's a repository if it's maintained (archived repository will be rejected).

**Comment by mcanouil** [comment]
Thanks!

**Comment by mcanouil** [comment]
Added to #36 to be released later next week.
