### ISSUE TITLE
Add new book format 

### ISSUE THREAD

**Issue by emdelponte** [mcanouil/awesome-quarto#353]
### Link to suggestion

https://github.com/emdelponte/epidemiology-R

### Targeted section

Real life examples/Book formats

### Describe your suggestion

I wish to include my book made with Quarto in the list of book format. The name is "R for Plant Disease Epidemiology". the link to book is https://r4pde.netlify.app/ 

### Checklist

- [X] checked if your suggestion is not already listed in __Awesome Quarto__ list.
- [X] checked if it can fit in an existed section or suggest a new section and explain why your item does not fit into one and what would be the interest of your new section.
- [X] checked when it's a repository if it's maintained (archived repository will be rejected).

**Comment by mcanouil** [comment]
Thanks for the suggestion.

There is already "classic" book example and yours seems to not use any customise things unfortunately.
