### ISSUE TITLE
add quart_borg reveal.js template

### ISSUE THREAD

**Issue by morrisLuke** [mcanouil/awesome-quarto#354]
### Link to suggestion

https://github.com/morrisLuke/quart_borg

### Targeted section

Templates/Presentations

### Describe your suggestion

This [Mork Borg](https://morkborg.com/)-inspired slide theme was built for [Quarto](https://quarto.org/) users to build [Reveal.js](https://revealjs.com/) slides with the color scheme from an unhealthily apocalyptic and metal tabletop role-playing game.

### Checklist

- [X] checked if your suggestion is not already listed in __Awesome Quarto__ list.
- [X] checked if it can fit in an existed section or suggest a new section and explain why your item does not fit into one and what would be the interest of your new section.
- [X] checked when it's a repository if it's maintained (archived repository will be rejected).

**Comment by mcanouil** [comment]
Thanks for the suggestio!
Unfortunately I can't add this as it is not a template per se.
See <https://quarto.org/docs/extensions/listing-revealjs.html> and <https://quarto.org/docs/extensions/formats.html>.
