### ISSUE TITLE
Custom title page for LaTeX documents/books

### ISSUE THREAD

**Issue by mcanouil** [mcanouil/awesome-quarto#37]
### Link to suggestion

https://github.com/nmfs-opensci/quarto_titlepages

### Targeted section

Extensions

### Describe your suggestion

This template makes a custom title page using the information in the YAML (from the xyz.qmd for a single doc and from index.qmd for a [Quarto](https://quarto.org/) book).

### Checklist

- [X] checked if your suggestion is not already listed in __Awesome Quarto__ list.
- [X] checked if it can fit in an existed section or [open a discussion](https://github.com/mcanouil/awesome-quarto/discussions/new?category=ideas) to suggest any new sections..
- [X] checked when it's a repository if it's maintained (archived repository will be rejected).

**Comment by eeholmes** [comment]
Ok, v2.0 is ready and extension seems to be working.
https://github.com/nmfs-opensci/quarto_titlepages

Thanks for your help! I added you to the acknowledgements/author list.
