### ISSUE TITLE
resource maybe worth adding

### ISSUE THREAD

**Issue by andreashandel** [mcanouil/awesome-quarto#379]
### Link to suggestion

https://github.com/MMJansen/workshop_quarto_slides

### Targeted section

Tutorials & workshops

### Describe your suggestion

seems relevant/useful

### Checklist

- [X] checked if your suggestion is not already listed in __Awesome Quarto__ list.
- [X] checked if it can fit in an existed section or suggest a new section and explain why your item does not fit into one and what would be the interest of your new section.
- [X] checked when it's a repository if it's maintained (archived repository will be rejected).

**Comment by mcanouil** [comment]
Thanks for the suggestion.

After going quickly over the slides, I am not going to add it as I don't see an adding value to the workshop/tutorials already in the list (I might have missed it though, if so please details/explain).
