### ISSUE TITLE
Add blog post on interactive molecular content

### ISSUE THREAD

**Issue by kjelljorner** [mcanouil/awesome-quarto#38]
### Link to suggestion

https://www.valencekjell.com/posts/2022-08-13-interactive/

### Targeted section

Blog posts

### Describe your suggestion

I made a blog post on using Quarto to include interactive content for molecular visualization. This is related to https://github.com/jmbuhr/quarto-molstar but the examples that I give are more advanced and need to make use of Observable JS.

### Checklist

- [X] checked if your suggestion is not already listed in __Awesome Quarto__ list.
- [X] checked if it can fit in an existed section or [open a discussion](https://github.com/mcanouil/awesome-quarto/discussions/new?category=ideas) to suggest any new sections..
- [X] checked when it's a repository if it's maintained (archived repository will be rejected).

**Comment by mcanouil** [comment]
Thanks!
I would put it more in the "real life examples" as a concrete use of quarto and quarto-molstar, what do you think?

PS: About your blog, you may not know but instead of utterance, there is discuss? The former send the comments to "Issues" while the latter send the comments to "Discussion" 😉

**Comment by kjelljorner** [comment]
That sounds good to me! Do you mean https://giscus.app by the way? It doesn't seem mature?

**Comment by kjelljorner** [comment]
Also, I don't user quarto-molstar, only learned about it after I made the post and the author commented on Twitter 😄

**Comment by mcanouil** [comment]
Ok, I'll see where I put it when I'll add it for the next release.

Yes I meant giscuss. I don't think it's more likely to break than utterance.
GitHub is also working heavily on "Issues", not only "Discussion".
I switched to giscuss because it does not open issues (it's confusing to have actual issues and discussions issues) in the repository while keeping the discussions in it.
But all this is only my opinion thus likely biased by the way I am using GitHub & Co.

**Comment by mcanouil** [comment]
> Also, I don't user quarto-molstar, only learned about it after I made the post and the author commented on Twitter 😄

How I see, so maybe more appropriate in blog post section then 🤔

**Comment by kjelljorner** [comment]
> > Also, I don't user quarto-molstar, only learned about it after I made the post and the author commented on Twitter 😄
> 
> How I see, so maybe more appropriate in blog post section then 🤔

Whatever you think is most appropriate!
