### ISSUE TITLE
A Tufte Inspired Manuscript extension

### ISSUE THREAD

**Issue by fredguth** [mcanouil/awesome-quarto#386]
### Link to suggestion

https://github.com/fredguth/tufte-inspired

### Targeted section

Extensions

### Describe your suggestion

A Tufte inspired manuscript extension with Typst and Html formats

### Checklist

- [X] checked if your suggestion is not already listed in __Awesome Quarto__ list.
- [X] checked if it can fit in an existed section or suggest a new section and explain why your item does not fit into one and what would be the interest of your new section.
- [X] checked when it's a repository if it's maintained (archived repository will be rejected).

**Comment by mcanouil** [comment]
Thanks.
The list no longer takes extensions, but you can submit to https://github.com/mcanouil/quarto-extensions which is referenced in the list.
