### ISSUE TITLE
Add new PDF template example

### ISSUE THREAD

**Issue by andrewheiss** [mcanouil/awesome-quarto#80]
### Link to suggestion

https://github.com/andrewheiss/hikmah-academic-quarto

### Targeted section

Templates/PDF Documents

### Describe your suggestion

Following [the discussion here](https://github.com/quarto-dev/quarto-cli/discussions/2117), here's a custom PDF/LaTeX template that supports `biblatex-chicago`.

### Checklist

- [X] checked if your suggestion is not already listed in __Awesome Quarto__ list.
- [X] checked if it can fit in an existed section or [open a discussion](https://github.com/mcanouil/awesome-quarto/discussions/new?category=ideas) to suggest any new sections..
- [X] checked when it's a repository if it's maintained (archived repository will be rejected).

**Comment by mcanouil** [comment]
Thanks, added and merged!
it will be featured in the next release.
