### ISSUE TITLE
Suggestion:  Python for Data Analysis, 3E

### ISSUE THREAD

**Issue by ivelasq** [mcanouil/awesome-quarto#85]
### Link to suggestion

https://wesmckinney.com/book/

### Targeted section

Real life examples/Book formats

### Describe your suggestion

I wish to see  Python for Data Analysis on the list because it is an example of a Quarto book focusing on Python.

### Checklist

- [X] checked if your suggestion is not already listed in __Awesome Quarto__ list.
- [X] checked if it can fit in an existed section or [open a discussion](https://github.com/mcanouil/awesome-quarto/discussions/new?category=ideas) to suggest any new sections..
- [X] checked when it's a repository if it's maintained (archived repository will be rejected).

**Comment by mcanouil** [comment]
Thanks for this suggestions!
Added in #99.
