### ISSUE TITLE
QRCode.js shortcode extension

### ISSUE THREAD

**Issue by mcanouil** [mcanouil/awesome-quarto#92]
### Link to suggestion

https://github.com/jmbuhr/quarto-qrcode

### Targeted section

Extensions

### Describe your suggestion

QRCode.js shortcode extension

### Checklist

- [X] checked if your suggestion is not already listed in __Awesome Quarto__ list.
- [X] checked if it can fit in an existed section or [open a discussion](https://github.com/mcanouil/awesome-quarto/discussions/new?category=ideas) to suggest any new sections..
- [X] checked when it's a repository if it's maintained (archived repository will be rejected).

**Comment by jmbuhr** [comment]
added via https://github.com/mcanouil/awesome-quarto/pulls
(sorry, I didn't see the issue before I made the PR)

**Comment by mcanouil** [comment]
No worries, the issues I make are simply a to-do list, if the author make a PR, it's fine.

**Comment by jmbuhr** [comment]
Thanks for being so active in the community! :) 
Knowing that this list exists is encouraging for creating an extension for something that might be useful for others instead of copy and pasting a private code snippet.
